### ISSUE TITLE
Add support for SVG images

### ISSUE THREAD

**Issue by kevva** [kevva/resize-img#1]

**Comment by kevva** [comment]
I've found this https://github.com/svg/svgo/blob/master/plugins/transformsWithOnePath.js but it only supports SVGs with one path in them which makes it pretty useless anyway.

If https://github.com/tmpvar/jsdom/pull/1445 gets merged we could probably use it in conjunction with https://github.com/wout/svg.js.

**Comment by sindresorhus** [comment]
Why would you want to resize SVG? They're already scalable on use.

**Comment by kevva** [comment]
Can't remember why to be honest, lol. Oh well, this can probably be closed.
