### ISSUE TITLE
Feature enhancement - convert file format on resize

### ISSUE THREAD

**Issue by jimsugg** [kevva/resize-img#5]
I need the ability to specify output file format, primarily so that when resizing pngs or bmps, I can output as jpg (for compact thumbnail generation.) I have this implemented - it is pretty straightforward, and also easy to convert between all formats. I have added an optional 'out' property to opts, which can be set to 'jpg', 'png', or 'bmp'. It works pretty well - it just selects any of the three output encoder possibilities. I have also added basic tests for this.

This is in the convertFormat branch on my fork.

Options for deployment:
1. I can submit a pull request so it will be integrated into this package.
2. I can publish as a separate package: resize-convert-img.

What is your preference?

**Comment by kevva** [comment]
Let me think about it. What's the downside of publishing it as a separate module that only does converting between formats? I guess you'd have to parse the image an extra time but does that affect performance that much?

**Comment by jimsugg** [comment]
I would say that the thumbnail generation use case is a very compelling one, and the way that resize-img is written, it is just very straightforward to select the output format for the re-encode which is necessary anyway. Certainly in the project I am doing now I don't want to do it in two steps because it is unnecessary complexity, and sometimes I have a lot of thumbnails to generate. If the only publicly available modules did it separately, I would use my own private version.

Now, I can also see that there is a good argument for having a separate module that does only conversion, because some use cases might not need the resize operation. I thought about making the resize optional, but that just seemed to be getting too complex and off-track.

So I certainly see your point - that's why I was asking. I tend to lean to publishing as a separate module for those reasons, but I really wanted to get your thoughts because I was having trouble deciding as well.
